site_name: GeoNEX Docs
nav:
    - Home: index.md
    - User Guide: userguide.md
    - Algorithm Reference: algo-ref.md
    - Core-API Reference: core-api.md
    - Development Reference: devel-ref.md
    - Admin Handbook: admin.md
    - Tutorials: tutorials.md
    - FAQ: faq.md
    - About: about.md
theme: readthedocs